### ISSUE TITLE
Build fail with 1.11.3 without --with-stream_ssl_module

### ISSUE THREAD

**Issue by thusithapk** [MelonSmasher/NginxInstaller#2]
I had to add --with-stream_ssl_module to your script to get the build process completed.

`./configure --user=nginx --group=nginx --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --without-http_scgi_module --without-http_uwsgi_module --with-http_gzip_static_module --with-pcre-jit --with-http_ssl_module --with-pcre --with-file-aio --with-http_realip_module --with-http_v2_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module;`

https://trac.nginx.org/nginx/ticket/1032

**Comment by MelonSmasher** [comment]
I've added this argument to the compile options, though I think the issue was fixed upstream in later releases on NGINX.

c643a0a
